stages:
  - build
  - deploy

services:
  - docker:dind

generate_version:
  stage: build
  image: docker:latest
  before_script:
    - docker info || { echo "Docker is not running, it's necessary to verify"; exit 1; }
    - docker-compose --version || { echo "Docker Compose is not installed"; exit 1; }
  script:
    - export VERSION=$(git describe --tags --always --dirty)
    - echo "Generated version $VERSION"
    - echo "$VERSION" > VERSION
  artifacts:
    paths:
      - VERSION
  only:
    - main

build:
  stage: deploy
  image: docker:latest
  needs: ["generate_version"]
  dependencies:
    - generate_version
  script:
    - export VERSION=$(cat VERSION)
    - echo "SPRING_MAIL_HOST=${SPRING_MAIL_HOST}"
    - echo "SPRING_MAIL_PORT=${SPRING_MAIL_PORT}"
    - echo "SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}"
    - echo "SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}"
    - echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}"
    - echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}"
    - echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}"
    - echo "SPRING_MAIL_PROPERTIES_MAIL_SMTP_LOCALHOST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_LOCALHOST}"
    - docker build --build-arg "SPRING_MAIL_HOST=${SPRING_MAIL_HOST}" --build-arg "SPRING_MAIL_PORT=${SPRING_MAIL_PORT}" --build-arg "SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}" --build-arg "SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}" --build-arg "SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}" --build-arg "SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}" --build-arg "SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST}" --build-arg "SPRING_MAIL_PROPERTIES_MAIL_SMTP_LOCALHOST=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_LOCALHOST}" -t "gravel3497/glowin:${VERSION}" -t "gravel3497/glowin:latest" .
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - docker push "gravel3497/glowin:latest"
  only:
    - main
