name: glowin

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: glowin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    restart: always

  app:
    image: gravel3497/glowin:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/glowin
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

  frontend:
    image: gravel3497/glowinfront:latest
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://IP_PUBLICA_EC2:8080
    depends_on:
      - app
    restart: always